swagger: "2.0"
info:
  description: "This is a school project API about TodoList Management."
  version: "1.0.0"
  title: "TodoList API"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "127.0.0.1"
basePath: "/v2"
schemes:
- "https"
- "http"
paths:
  /todo-list/{list_id}:
    get:
      tags:
      - "todo-list"
      summary: "Ermittelt anhand der übergebenen ID, die entsprechende Todo-Liste"
      operationId: "getTodoList"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "path"
        name: "list_id"
        required: true
        type: "integer"
      responses:
        "200":
          description: "successful operation"
        "405":
          description: "invalid input"
  /todolist/{list_id}:
    delete:
      tags:
      - "todo-list"
      summary: "Löscht die Liste mit einer angegebenen ID"
      operationId: "deleteTodoList"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "list_id"
        in: "path"
        required: true
        type: "integer"
      responses:
        "200":
          description: "successful operation"
        "405":
          description: "invalid input"
  /todolist/:
    post:
      tags:
      - "todo-list"
      summary: "Fügt eine neue Todo-Liste hinzu"
      operationId: "addTodoList"
      consumes:
      - "application/xml"
      - "application/json"
      responses:
        "200":
          description: "successful operation"
        "405":
          description: "invalid input"
  /todo-list/{list_id}/entry/:
    post:
      tags:
      - "todo-list"
      summary: "Fügt einen Eintrag zu einer bestehenden Todo-Liste hinzu"
      operationId: "addEntryToTodoList"
      consumes:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "list_id"
        in: "path"
        required: true
        type: "integer"
      responses:
        "200":
          description: "successful operation"
        "405":
          description: "invalid input"
  /todo-list/{list_id}/entry/{entry_id}:
    put:
      tags:
      - "todo-list"
      summary: "Aktualisiert einen Eintrag aus einer bestehenden Todo-Liste"
      operationId: "updateEntryFromTodoList"
      consumes:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "list_id"
        in: "path"
        required: true
        type: "integer"
      - name: "entry_id"
        in: "path"
        required: true
        type: "integer"
      responses:
        "200":
          description: "successful operation"
        "405":
          description: "invalid input"
